### ISSUE TITLE
Error File not found disks/data [partialy solved]

### ISSUE THREAD

**Issue by panigrc** [mblaschke/vagrant-development#108]
In windows 7 when I try to open the vm with workstation, or do any jobs with vagrant command line (except up) I got a "file not found" error, after checking the logs I saw that there is a problem with the disks/data file.
The problem is that in the ubuntu1404-docker.vmx the file path to data is 
`scsi0:1.filename = "C:/myproject/disks/data"`

If I change it to
`scsi0:1.filename = "C:\myproject\disks\data"`

The problem is that everytime I run vagrant up the .vmx file is regenerated.
The same problem must exist in the ubuntu 16.04 version.

**Comment by panigrc** [comment]
A quick and dirty solution is to replace all the slashes with back-shlashes in the Vagrantfile
```ruby
            v.vmx['scsi0:1.filename'] = "#{VAGRANT_ROOT}/disks/data".gsub(/\//, '\\')
```

**Comment by josefglatz** [comment]
@PanadeEdu can u reproduce this behaviour in Windows?

**Comment by panigrc** [comment]
I can't reproduce this problem anymore so I close the issue.
