### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by Mte90** [mblaschke/vagrant-development#109]
It is not clear how to use that project, the docs is incomplete on https://webdevops.io/projects/vagrant-docker-vm/

Also on this repo there is more documentation but there is no example of using. There is only change the settings on vm.yml without any examples about cases.
As example I have a project with docker support how I can add it on that?

**Comment by josefglatz** [comment]
Hi, @Mte90 ,

I understand you. Did you already read https://webdevops-documentation.readthedocs.io/en/latest/ ?

**Comment by Mte90** [comment]
I don't remember, in an year is difficult to remember what I read.
