### ISSUE TITLE
vagrant up fails due to forbidden download

### ISSUE THREAD

**Issue by DevOnWheels** [mblaschke/vagrant-development#110]
I tried "vagrant up" and failed downloading https://vagrantcloud.com/box-cutter/boxes/ubuntu1604/versions/2.0.26/providers/virtualbox.box (403 Forbidden). Could you provide an alternative location or workaround for that problem, please? :)

**Comment by adyp** [comment]
Looks like the Boxcutter project decided to stop shipping pre-built images:
* https://github.com/boxcutter/ubuntu#current-boxes
* https://github.com/boxcutter/ubuntu/issues/133#issuecomment-339929663

Other projects started to migrate towards _bento/ubuntu_ Vagrant boxes.
