### ISSUE TITLE
Timezone has to be defined

### ISSUE THREAD

**Issue by vasilvestre** [mblaschke/vagrant-development#111]
Hi,

Not really an issue I need help for. I've living in France and we have different timezone depending of season. It caused some bugs, I had to set it manually.
It could be great if vm.yml could be used to set the timezone.

I got no knowledge for ansible, vagrant etc so I don't make it myself.
Thanks to consider this idea.

**Comment by adyp** [comment]
You can give a try to the PR #112 (checkout the branch _feature/define-custom-timezone_ from the forked repo `bsdcon/vagrant-docker-vm`) -- it will adapt when provisioning the VM with a defined value for _VM.timezone_ in `vm.yml`.

To immediately change on a live VM you could run `dpkg-reconfigure tzdata` in an interactive shell.
