### ISSUE TITLE
Q: support for enterprise environment ?

### ISSUE THREAD

**Issue by adyp** [mblaschke/vagrant-development#116]
This is actually a question related to project policies: is the project willing to integrate changes proposed by 3rd parties to improve the experience using it in enterprise (work) environments? Or is it intended to only focus on individuals' usage ?

Sample proposed changes would include (not an exhaustive list):
* support for running in isolation (limited access to Internet / only via proxy)
* alignment with corporate policies for infra (DNS settings inheritance, using internal Docker registries, using a proxy service, etc.)
* consistent versioning in project and dependencies (submodules) -- teams making use of it prefer to validate their work against specific versions (instead of simply using the default branch which is a moving target over time)

We would like to push back such improvements upstream instead of keeping it only in our fork. The answer would help us clarify the strategy in long term.

PS: sorry for abusing the issue tracker but frankly I did not know whom/how to ask otherwise.

**Comment by mblaschke** [comment]
We will integrate push requests if they make sense :)
But join Slack to discussion specific features.

Sorry for the delay.. i was quite busy with job specific topics
