### ISSUE TITLE
vmrun issue

### ISSUE THREAD

**Issue by elimentz** [mblaschke/vagrant-development#117]
Trying to get this box up and running but I'm having some issues with it. Vagrant can't start the box for unknown reasons:

```
➜  vagrant-docker git:(ubuntu-16.04) ✗ vagrant up
Bringing machine 'default' up with 'vmware_fusion' provider...
==> default: Box 'bento/ubuntu-16.04' could not be found. Attempting to find and install...
    default: Box Provider: vmware_desktop, vmware_fusion, vmware_workstation
    default: Box Version: >= 0
==> default: Loading metadata for box 'bento/ubuntu-16.04'
    default: URL: https://vagrantcloud.com/bento/ubuntu-16.04
==> default: Adding box 'bento/ubuntu-16.04' (v201710.25.0) for provider: vmware_desktop
    default: Downloading: https://vagrantcloud.com/bento/boxes/ubuntu-16.04/versions/201710.25.0/providers/vmware_desktop.box
==> default: Successfully added box 'bento/ubuntu-16.04' (v201710.25.0) for 'vmware_desktop'!
==> default: Cloning VMware VM: 'bento/ubuntu-16.04'. This can take some time...
==> default: Checking if box 'bento/ubuntu-16.04' is up to date...
==> default: Verifying vmnet devices are healthy...
==> default: Preparing network adapters...
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Starting the VMware VM...
An error occurred while executing `vmrun`, a utility for controlling
VMware machines. The command and output are below:

Command: ["start", "/Users/deerjohn/vagrant/vagrant-docker/.vagrant/machines/default/vmware_fusion/cf964199-94c9-4ef9-8b17-62d73a02e508/ubuntu-16.04-amd64.vmx", "nogui", {:notify=>[:stdout, :stderr], :timeout=>45}]

Stdout: 2018-01-02T12:17:14.128| ServiceImpl_Opener: PID 7681
Error: The operation was canceled

Stderr: 
```

if I enable the vmware gui in config, I get a popup with the following error message: `The file specified is not a virtual disk`

I also tried using various other boxes, but I get the same error for all of them. I did make some modifications to the `vm_defaults.yml` file, but nothing out of the ordinary (git credentials, VM name,..)

Any help is appreciated.

**Comment by adyp** [comment]
Could you please post more info such as:
- version of Vagrant, VMware Fusion, [Mac]OS
- is this the first time you are using it ? has it been running for you in the past ?
- any upgrades you performed recently / since it was last working ?
- output of `find disk -ls` in the git clone directory
- how did you clone the project (did you use the `--recursive` parameter for the *git clone* command line) ?

It looks like VMware does not like or find the additional virtual disk file.

**Comment by elimentz** [comment]
I forgot the `--recursive` parameter. Apologies for the inconvenience
