### ISSUE TITLE
Documentation Structure should be improved

### ISSUE THREAD

**Issue by PanadeEdu** [mblaschke/vagrant-development#21]
Problem Description:
The current Documentation provides Informations in a One Page Design. This could be Improved to extend the Repository with a Documentation Folder which Provides Sub-Pages for each Topic.

Possible Solution:
Extract the main Parts from Documentation and split them in seperate Files such as (only an Example):
- Installation
- Usage
- Networking
- Additional Functions
- Changelog

Like the SRP (Single Responsibility Principle), it improves readability if one Page only contains one responsibility. 
The main Page should only contain:
- Project Description
- Short Introduction
- Table of Contents

**Comment by mblaschke** [comment]
Improved some documentation 4f31051dc3404fdd797c2b242f60b9654dba1f83
