### ISSUE TITLE
Box SSH breaks wenn going from no Internet to Internet

### ISSUE THREAD

**Issue by PanadeEdu** [mblaschke/vagrant-development#23]
Problem: 
When running the Box without an internet Connection, there is no problem in using it. As soon as Internet is connected, it looses every SSH Connection and I am unable to connect again.

Workaround: 
Reboot the entire Vagrant Box 

Technical Env:
Windows 8.1 
running VagrantBox 
with Virtual Box as Provider

**Comment by mblaschke** [comment]
I think this is a virtualbox networking issue.

VMware automatically switches from ethernet to wifi and back within some seconds.

Workaround: Vagrant Reload

**Comment by PanadeEdu** [comment]
Vagrant up seems to load different tasks without internet connection. Such as git ssh key fetching.

**Comment by mblaschke** [comment]
Related to #22
