### ISSUE TITLE
Issue with the "Fix filesystem rights" Task

### ISSUE THREAD

**Issue by PanadeEdu** [mblaschke/vagrant-development#29]
System: Windows 10
Provider: VMWare Workstation 11

On boot I get the following error Output:

==> default: TASK: [user | Fix filesystem rights (/home/vagrant)] **************************
==> default: failed: [localhost] => {"changed": true, "cmd": ["chown", "-R", "vagrant:vagrant", "/home/vagrant/.config/"], "delta": "0:00:00.002452", "end": "2015-06-06 19:09:50.177104", "rc": 1, "start": "2015-06-06 19:09:50.174652", "warnings": ["Consider using file module with owner rather than running chown"]}
==> default: stderr: chown: cannot access ���/home/vagrant/.config/���: No such file or directory
==> default: ...ignoring
==> default:

This doesnyt break the Provisioning, but the File also doesnt exist inside the VM.

**Comment by PanadeEdu** [comment]
Testing this clone worked:
git clone --config core.autocrlf=false https://github.com/mblaschke/vagrant-development.git

**Comment by mblaschke** [comment]
This directroy seems to be created (sometimes) by ansible or vagrant with the wrong rights
This task is set to 'ignore errors' so you can ignore any issues here

Maybe i should rewrite this task to fix any errors/warnings
