### ISSUE TITLE
Ansible fails at Task "Start firewall"

### ISSUE THREAD

**Issue by PanadeEdu** [mblaschke/vagrant-development#30]
Host System: Windows 10 RC1
Provider: VMWare Workstation 11

The Ansible Task at initial Provisioning fails in "Start firewall" with following output:

==> default: TASK: [firewall | Start firewall] *********************************************
==> default: failed: [localhost] => {"changed": true, "cmd": ["service", "firewall-vm", "restart"], "delta": "0:00:00.004728", "end": "2015-06-06 19:36:05.270582", "rc": 127, "start": "2015-06-06 19:36:05.265854", "warnings": ["Consider using service module rather than running service"]}
==> default: stderr: env: /etc/init.d/firewall-vm: No such file or directory
==> default:
==> default: FATAL: all hosts have already failed -- aborting
==> default:
==> default: PLAY RECAP ********************************************************************
==> default:            to retry, use: --limit @/root/playbook.retry
==> default: localhost                  : ok=95   changed=75   unreachable=0    failed=1

**Comment by PanadeEdu** [comment]
Problem solved

Source: Wrong Line endings with git clone
Solution: Changing auto crlf to false and checking out the provision directory again.

Suggesting a troubleshoot section in the docs

**Comment by mblaschke** [comment]
Can you check if it is possible to set this setting for the "git clone" command only?

**Comment by PanadeEdu** [comment]
Testing this clone worked:
git clone --config core.autocrlf=false https://github.com/mblaschke/vagrant-development.git
