### ISSUE TITLE
Is there a better solution to determine the VM Provider?

### ISSUE THREAD

**Issue by PanadeEdu** [mblaschke/vagrant-development#40]
When using VMWare, Vagrant sometimes trys to use VirtualBox as Provider even though there is not VirtualBox installed. This even happens if the VM Software is Installed first and Vagrant after. 

I observed this on Windows and as well on Mac OSX. 
Removing the VirtualBox Provider Settings will fix this. 

Maybe a solution could be an Optional vm.yml setting or an Vagrantfile Constant.

**Comment by mblaschke** [comment]
you have to startup vagrant via:

Windows:
`vagrant up --provider=vmware_workstation`
or as env:
`VAGRANT_DEFAULT_PROVIDER=vmware_workstation`

MacOS:
`vagrant up --provider=vmware_fusion`
or as env:
`VAGRANT_DEFAULT_PROVIDER=vmware_fusion`

**Comment by jousch** [comment]
The env variable can be placed in your user config (e.g.  ~/.bashrc)
