### ISSUE TITLE
[DOCUMENTATION] Add info how to start dev-vm without showing the GUI of Parallels

### ISSUE THREAD

**Issue by josefglatz** [mblaschke/vagrant-development#56]

**Comment by mblaschke** [comment]
Currently not possible because of upstream issue (missing feature in Parallels Desktop):
see Parallels/vagrant-parallels#39

**Comment by josefglatz** [comment]
When I start the vm from commandline or tools like Vagrant Manager or other helper scripts, the Parallels Desktop GUI isn't shown.

I think we could close this issue therefore?!
