### ISSUE TITLE
Reverse proxy didn't try to request website if the first attempt fails

### ISSUE THREAD

**Issue by josefglatz** [mblaschke/vagrant-development#64]
# Problem

Consider the following scenario:
1. You start _vagrant-development_
2. Forget to start your docker
3. Request a http://foo.vm/
4. Start docker containers
5. _vagrant-development_ reverse proxy throws 503 even if you force-refresh quite a few times in browser.
6. After force-refreshing (quite agressive 10-15 times) the reverse proxy tries to request the website from docker container

Is there any treshold time or request treshold which prevents the reverse proxy to request website from the docker container?

**Comment by mblaschke** [comment]
Docker containers need some seconds to be up (see `docker-compose logs`). Reverse proxy should get a running connection to docker containers when they're up.

Please check if docker container were fully running - php-fpm need some times due to runtime provisioning.

**Comment by josefglatz** [comment]
ok thx, will check

**Comment by josefglatz** [comment]
Thx for your quick answer! That was it
