### ISSUE TITLE
Problem during provisioning

### ISSUE THREAD

**Issue by tpinne** [mblaschke/vagrant-development#71]
I followed the description from https://markus-blaschke.de/2015/06/20/vagrant-docker-development-vm/ and get the following error during `vagrant up`. I don't have any idea how to proceed.

System: OS X 10.11
VM: VirtualBox 5.10

```
...
==> default: changed: [localhost] => (item=negotiation)
==> default: changed: [localhost] => (item=setenvif)
==> default: changed: [localhost] => (item=vhost_alias)
==> default: changed: [localhost] => (item=ssl)
==> default: changed: [localhost] => (item=proxy)
==> default: changed: [localhost] => (item=proxy_http)
==> default: changed: [localhost] => (item=rewrite)
==> default:
==> default: TASK: [docker-proxy | Create /var/www/empty/ directory] ***********************
==> default: failed: [localhost] => {"failed": true, "gid": 20, "group": "dialout", "mode": "0755", "owner": "501", "path": "/var/www/empty", "size": 68, "state": "directory", "uid": 501}
==> default: msg: chown failed
==> default:
==> default: FATAL: all hosts have already failed -- aborting
==> default:
==> default: PLAY RECAP ********************************************************************
==> default:            to retry, use: --limit @/root/playbook.retry
==> default:
==> default: localhost                  : ok=100  changed=57   unreachable=0    failed=1
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

The only thing I changed was in `vm.yml` the following lines. Because my home directory couldn't be mapped via NFS because all my other projects live somewhere deeper in my homedir and there have been other NFS exports which then conflicted.

```
  sharedFolder:
    #- { type: 'home' }
    - { type: 'nfs', src: '~/Sites/_dev', target: '/var/www' }
```

Besides of that I just started the machine.

Any hints on this?

**Comment by mblaschke** [comment]
Please try again with newest commit :)

BTW: I'm not shure if '~/Sites/_dev' is working, if not -> use full paths :)

**Comment by mblaschke** [comment]
OH BTW:
If you want to use Docker (and your files should be mounted into the VM) you have to use same paths for `src` and `target`. Docker runs on the VM and is searching inside the VM for host mounted shares so it must be the same.

So it's also a good idea  to use full paths because ~ is not possible for `target`
