### ISSUE TITLE
Using PHP7 in the dev-vm

### ISSUE THREAD

**Issue by ulrikkold** [mblaschke/vagrant-development#82]
I am trying to start a new TYPO3 v8.0 (which requires PHP7) by using the `composer create-project` command in the `~/app` folder of the dev-vm.

This fails as the dev-vm does not supply the required PHP version. Is there a really obvious way to get this working? Changing the VM-image or something else? I have not been able to wrap my head around the plethora of options, settings and config files.

Over at the TYPO3-docker-boilerplate project I found [this guide](https://github.com/webdevops/TYPO3-docker-boilerplate/issues/112) to using a PHP7-configured Docker image - but it seems convoluted to log in to  a docker image in a vagrant machine and then run the `composer create-project` in there. I would like to be able to do this directly in the dev-vm.

I guess it is also just a matter of time before PHP7 is needed for other projects.
Thanks in advance :-)

**Comment by PanadeEdu** [comment]
We provide the TYPO3-docker-boilerplate. By configuring the Dockerfile you can set another base image, some of which who also provide php7. We are currently working on some more base images that provide php7, but some of them are instable just yet. 

A small quickstart guide for the TYPO3 Docker Boilerplate can be found here:
https://webdevops.io/projects/typo3-docker-boilerplate/

We are currently working on a more advanced documentation, but for now the most recent documentation is the one residing as markdown in the repository.

**Comment by mblaschke** [comment]
Try `composer create-project --ignore-platform-reqs`

**Comment by ulrikkold** [comment]
I will try the `--ignore-platform-reqs` option when I find the time. That should do it, though ...

**Comment by mblaschke** [comment]
PHP 7 is installed in `ubuntu-16.04` (default php version)
