### ISSUE TITLE
vagrant up failed after docker compose and other errors

### ISSUE THREAD

**Issue by tinpansoul** [mblaschke/vagrant-development#89]
Hi!

I'm using OS 10.11.6, Vagrant 1.8.5 and branch ubuntu-16.04 from this repo.

Changed only `VM.cpu`, `VM.memory`, `VM.data.size`, `VM.portForwarding` from `vm.yml`-file.

Uploaded full log into gist:
– [After this error vagrant up failed](https://gist.github.com/TrogWarZ/0f48842a0400c6a5bb534b0fb7af8088#file-vagrant-docker-vm-16-error-log-L702-L706)
– [Main error with docker-compose](https://gist.github.com/TrogWarZ/0f48842a0400c6a5bb534b0fb7af8088#file-vagrant-docker-vm-16-error-log-L685)
– [Failed docker stop service](https://gist.github.com/TrogWarZ/0f48842a0400c6a5bb534b0fb7af8088#file-vagrant-docker-vm-16-error-log-L530)
– [Failed docker stop service](https://gist.github.com/TrogWarZ/0f48842a0400c6a5bb534b0fb7af8088#file-vagrant-docker-vm-16-error-log-L559)
– [Failed docker storage creation](https://gist.github.com/TrogWarZ/0f48842a0400c6a5bb534b0fb7af8088#file-vagrant-docker-vm-16-error-log-L546)
– [Strange error about deprecated flag 1](https://gist.github.com/TrogWarZ/0f48842a0400c6a5bb534b0fb7af8088#file-vagrant-docker-vm-16-error-log-L342)
– [Strange error about deprecated flag 2](https://gist.github.com/TrogWarZ/0f48842a0400c6a5bb534b0fb7af8088#file-vagrant-docker-vm-16-error-log-L184)

How can i solve `/usr/bin/pip install -U docker-compose`-error? Or workaround?

**Comment by mblaschke** [comment]
Is this error already fixed with latest changes? Should be already fixed

**Comment by tinpansoul** [comment]
@mblaschke, thank you, i'll try this in a few days.

**Comment by tinpansoul** [comment]
Thanks for waiting!

Don't know which commit fixed error, but `/usr/bin/pip install -U docker-compose`-error now gone, thank you! `vagrant up` is now runs without fatal.

ps: all other errors are in place yet.
